<a href="https://colab.research.google.com/github/tmdgusya/-MD-/blob/main/autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
x = torch.tensor([1.], requires_grad=True)
x

tensor([1.], requires_grad=True)

In [5]:
x = torch.tensor([1.], requires_grad=True)
y=x**2
print(y)

print(x.grad)
y.backward()
print(x.grad) # x**2 를 미분한 2x 의 x 값에 1을 대입한 gradient 값

tensor([1.], grad_fn=<PowBackward0>)
None
tensor([2.])


In [6]:
x = torch.tensor([1.], requires_grad=True)
y = x**2
print(y)

z=3*y
print(z) # z 는 둘다 가지고 있음

z.backward()
print(x.grad)

tensor([1.], grad_fn=<PowBackward0>)
tensor([3.], grad_fn=<MulBackward0>)
tensor([6.])


In [7]:
y.grad

<ipython-input-7-10b3a7061f6d>:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:489.)
  y.grad


Y 는 leaf tensor 가 아니고 중간에 있는 텐서라 warning 이 나옴

In [8]:
x = torch.tensor([1.], requires_grad=True)
y = x**2
print(y)
y.retain_grad() # 이걸하면 y.grad 도 볼수 있다.

z=3*y
print(z) # z 는 둘다 가지고 있음

z.backward()
print(x.grad)

tensor([1.], grad_fn=<PowBackward0>)
tensor([3.], grad_fn=<MulBackward0>)
tensor([6.])


In [10]:
x = torch.tensor([1.], requires_grad=True)

with torch.no_grad():
    """
    모델을 테스트 할때에는 불필요하게 메모리를 쓸 필요 없음
    """
    y = x**2
    print(x.requires_grad)
    print(y)

print(x.requires_grad)

y = x**2
print(y)

x = torch.tensor([1.], requires_grad=True)
x.requires_grad=False
y = y**2
print(x.requires_grad)
print(y)

True
tensor([1.])
True
tensor([1.], grad_fn=<PowBackward0>)
False
tensor([1.], grad_fn=<PowBackward0>)
